// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11pDYCD9gaPxH76B__zMjJOfXVztmoTA',
    appId: '1:90299973757:web:6e2a28ea1d33e3b1abb114',
    messagingSenderId: '90299973757',
    projectId: 'ibm-malmoe-4166b',
    authDomain: 'ibm-malmoe-4166b.firebaseapp.com',
    storageBucket: 'ibm-malmoe-4166b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ3q9HrFn_EYBInNXEOzBFj8mw2-ApSmg',
    appId: '1:90299973757:android:1084a455da02b15eabb114',
    messagingSenderId: '90299973757',
    projectId: 'ibm-malmoe-4166b',
    storageBucket: 'ibm-malmoe-4166b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSL4nNFa4_KJhgJbvEln5Iw9lUWiPDpxI',
    appId: '1:90299973757:ios:86c1b6f3ef556069abb114',
    messagingSenderId: '90299973757',
    projectId: 'ibm-malmoe-4166b',
    storageBucket: 'ibm-malmoe-4166b.appspot.com',
    iosClientId: '90299973757-b092p8eo9n8oe2o577k5fsr3dpvl6rkl.apps.googleusercontent.com',
    iosBundleId: 'tech.neurothrone.ibmMalmoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSL4nNFa4_KJhgJbvEln5Iw9lUWiPDpxI',
    appId: '1:90299973757:ios:86c1b6f3ef556069abb114',
    messagingSenderId: '90299973757',
    projectId: 'ibm-malmoe-4166b',
    storageBucket: 'ibm-malmoe-4166b.appspot.com',
    iosClientId: '90299973757-b092p8eo9n8oe2o577k5fsr3dpvl6rkl.apps.googleusercontent.com',
    iosBundleId: 'tech.neurothrone.ibmMalmoe',
  );
}
