// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-MY7_ondpwTpxcFerYBnl2DN0VhSGvRk',
    appId: '1:587424333588:web:a688e7a8cf9a7a7a214c01',
    messagingSenderId: '587424333588',
    projectId: 'ibm-malmoe-30b69',
    authDomain: 'ibm-malmoe-30b69.firebaseapp.com',
    storageBucket: 'ibm-malmoe-30b69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKsIChWQj9ERz3DPQuRyxQVFRReq_qWAQ',
    appId: '1:587424333588:android:81dc5ba795edce79214c01',
    messagingSenderId: '587424333588',
    projectId: 'ibm-malmoe-30b69',
    storageBucket: 'ibm-malmoe-30b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3hyDIksdAasIZm51XvQXTM6w1fnGjwpQ',
    appId: '1:587424333588:ios:297537bb2c2a6cb3214c01',
    messagingSenderId: '587424333588',
    projectId: 'ibm-malmoe-30b69',
    storageBucket: 'ibm-malmoe-30b69.appspot.com',
    iosClientId: '587424333588-nkjf1qq25cvsdll5a2faavki24dtsuip.apps.googleusercontent.com',
    iosBundleId: 'tech.neurothrone.ibmMalmoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3hyDIksdAasIZm51XvQXTM6w1fnGjwpQ',
    appId: '1:587424333588:ios:297537bb2c2a6cb3214c01',
    messagingSenderId: '587424333588',
    projectId: 'ibm-malmoe-30b69',
    storageBucket: 'ibm-malmoe-30b69.appspot.com',
    iosClientId: '587424333588-nkjf1qq25cvsdll5a2faavki24dtsuip.apps.googleusercontent.com',
    iosBundleId: 'tech.neurothrone.ibmMalmoe',
  );
}
